SELECT JNO FROM J WHERE NOT EXISTS (
	SELECT * FROM SPJ WHERE spj.JNO=J.JNO 
	AND SNO IN(
			SELECT SNO FROM S WHERE CITY='天津'
	)
	AND PNO IN(
			SELECT PNO FROM P WHERE COLOR='红'
	)
);
SELECT JNO FROM J
	WHERE NOT EXISTS (
			SELECT *
			FROM SPJ,P,S
			WHERE SPJ.PNO=P.PNO AND P.COLOR='红' AND S.CITY='天津' AND S.SNO=spj.SNO
				AND spj.JNO=J.JNO
);