-- (1)找出所有供应商的姓名和城市
SELECT SNAME,CITY FROM S;
-- (2)所有零件的名称、颜色、重量
SELECT  PNAME,COLOR,WEIGHT FROM P;
-- (3)S1供应零件的工程
SELECT JNO FROM spj WHERE SNO='S1';
-- (4)使用J2使用的零件名称和数量
SELECT P.PNAME,spj.QTY FROM P,SPJ WHERE P.PNO=spj.PNO AND spj.JNO='J2';
-- (5)上海厂的所有零件号码
SELECT DISTINCT PNO FROM spj WHERE SNO IN(
		SELECT SNO FROM S WHERE CITY='上海'
);
-- (6)上海零件的工程
SELECT JNAME FROM J,SPJ,S WHERE J.JNO=spj.JNO and spj.SNO=S.SNO and S.CITY='上海';
-- (7)没有使用天津产零件的工程
SELECT JNO FROM J WHERE NOT EXISTS (
		SELECT * FROM SPJ,S WHERE spj.JNO=J.JNO AND spj.SNO=S.SNO AND S.CITY='天津'
);
-- (8)改红色零件为蓝色
SELECT * FROM P;
UPDATE P SET COLOR='蓝' WHERE COLOR='红';
SELECT * FROM P;

-- (9)S5给J4的零件P6改为为P3给
SELECT * FROM SPJ;
UPDATE spj SET SNO='S3' WHERE SNO='S5' AND JNO='J4' AND PNO='P6';
SELECT * FROM SPJ;
-- (10)删除供应商关系中S2的记录，然后从供应情况删除S2相关
DELETE FROM SPJ WHERE SNO='S2';
DELETE FROM S WHERE SNO='S2';
-- (11)插入一组元组
SELECT * FROM SPJ;
INSERT INTO SPJ VALUES ('S2', 'P4', 'J6', '200');
SELECT * FROM SPJ;

 